import asyncio

from app.models import Action, Company


class ArticleAgent:
    kind = "article"

    async def run(self, action: Action, company: Company) -> dict:
        await asyncio.sleep(2)
        topic = (action.target or {}).get("topic") or "your tracked topic"
        title = action.title.replace("Publish a how-to: ", "").replace(
            "Write a how-to article about ", ""
        )
        markdown = (
            f"# {title}\n\n"
            f"_Draft article for {company.name}_\n\n"
            f"## Why this matters\n\n{action.rationale or 'High-impact content gap.'}\n\n"
            f"## Outline\n\n"
            f"1. Introduction to {topic}\n"
            f"2. The challenge {company.name} customers face\n"
            f"3. Step-by-step walkthrough\n"
            f"4. Pitfalls and edge cases\n"
            f"5. Closing call-to-action\n\n"
            f"---\n_Generated by Felix article agent (stub)._\n"
        )
        return {
            "type": "article",
            "title": title,
            "markdown": markdown,
            "word_count_estimate": 1200,
        }
