"""CodePrAgent — executor that takes an ImprovementPlan produced by the
ImprovementAgent (stored on a prior Job's `result`), applies the edits to a
configured GitHub repo, pushes a feature branch, and opens a PR.
"""

from __future__ import annotations

import logging

from sqlalchemy.orm import Session

from app.models import Action, Company, Job, RepoConfig
from app.schemas import ImprovementPlan
from app.services import git_ops
from app.services import jobs as jobs_svc

logger = logging.getLogger(__name__)


class CodePrError(RuntimeError):
    def __init__(self, message: str, code: str = "code_pr_failed"):
        super().__init__(message)
        self.code = code


class CodePrAgent:
    kind = "code-pr"

    async def run(
        self,
        action: Action,
        company: Company,
        *,
        db: Session,
        job_id: str,
        improvement_job_id: str,
        **_: object,
    ) -> dict:
        # 1. Load + validate plan
        improvement_job = db.get(Job, improvement_job_id)
        if improvement_job is None:
            raise CodePrError(
                f"improvement job {improvement_job_id!r} not found",
                code="improvement_job_missing",
            )
        if improvement_job.status != "done":
            raise CodePrError(
                f"improvement job is {improvement_job.status!r}, expected 'done'",
                code="improvement_not_done",
            )
        if improvement_job.action_id != action.id:
            raise CodePrError(
                "improvement job is for a different action",
                code="improvement_action_mismatch",
            )
        try:
            plan = ImprovementPlan.model_validate(improvement_job.result or {})
        except Exception as e:
            raise CodePrError(
                f"improvement plan failed validation: {e}",
                code="plan_invalid",
            ) from e

        jobs_svc.append_event(db, job_id, "loading_plan", {"edit_count": len(plan.edits)})

        # 2. Load RepoConfig
        repo_cfg = db.query(RepoConfig).filter(RepoConfig.company_id == company.id).first()
        if repo_cfg is None:
            raise CodePrError(
                "no repo configured for this company",
                code="repo_not_configured",
            )

        slug = git_ops.parse_repo_slug(repo_cfg.repo_url)

        # 3. Clone writeable
        jobs_svc.append_event(db, job_id, "cloning_repo", {"repo_url": repo_cfg.repo_url})
        try:
            repo_dir = await git_ops.clone(repo_cfg.repo_url, repo_cfg.github_token)
        except git_ops.GitOpsError as e:
            raise CodePrError(f"clone failed: {e}", code="clone_failed") from e

        try:
            # 4. Apply edits
            edits_payload = [edit.model_dump() for edit in plan.edits]
            changed, skipped = await git_ops.apply_edits(repo_dir, edits_payload)
            jobs_svc.append_event(
                db,
                job_id,
                "applying_edits",
                {"changed": changed, "skipped": skipped},
            )

            if not changed:
                raise CodePrError(
                    f"no edits applied; skipped: {skipped}",
                    code="no_edits_applied",
                )

            # 5. Branch, commit, push
            branch = f"midas/{job_id[2:10]}" if job_id.startswith("j_") else f"midas/{job_id[:8]}"
            commit_message = (
                f"{plan.summary}\n\n{plan.rationale}\n\n"
                f"(generated by MIDAS from action {action.id})"
            )

            jobs_svc.append_event(db, job_id, "committing", {"branch": branch})
            try:
                await git_ops.commit_and_push(repo_dir, branch, commit_message)
            except git_ops.GitOpsError as e:
                raise CodePrError(f"push failed: {e}", code="push_failed") from e

            jobs_svc.append_event(db, job_id, "pushing", {"branch": branch})

            diff_stat = await git_ops.diff_summary(
                repo_dir, base_branch=repo_cfg.default_branch, head_branch=branch
            )
            diff = await git_ops.full_diff(
                repo_dir, base_branch=repo_cfg.default_branch, head_branch=branch
            )

            # 6. Open PR
            pr_body = _format_pr_body(plan, changed=changed, skipped=skipped)
            jobs_svc.append_event(db, job_id, "opening_pr", {"branch": branch})
            try:
                pr_url = await git_ops.open_pull_request(
                    slug.owner,
                    slug.repo,
                    repo_cfg.github_token,
                    head=branch,
                    base=repo_cfg.default_branch,
                    title=plan.summary,
                    body=pr_body,
                )
            except git_ops.GitOpsError as e:
                raise CodePrError(f"PR open failed: {e}", code="pr_open_failed") from e

        finally:
            git_ops.cleanup(repo_dir)

        return {
            "type": "code-pr",
            "title": plan.summary,
            "rationale": plan.rationale,
            "expected_impact": plan.expected_impact,
            "repo": f"{slug.owner}/{slug.repo}",
            "branch": branch,
            "pr_url": pr_url,
            "pr_body": pr_body,
            "files_changed": changed,
            "files_skipped": skipped,
            "diff_stat": diff_stat,
            "diff": diff,
        }


def _format_pr_body(plan: ImprovementPlan, *, changed: list[str], skipped: list[str]) -> str:
    lines = [
        plan.rationale,
        "",
        f"**Expected impact:** {plan.expected_impact}",
        "",
        "### Files changed",
    ]
    lines += [f"- `{p}`" for p in changed] or ["(none)"]
    if skipped:
        lines += ["", "### Skipped"]
        lines += [f"- {s}" for s in skipped]
    lines += ["", "_Generated by MIDAS · by Peec._"]
    return "\n".join(lines)
